Fix message spy wrong who bug
TonkaSource/TonkaSourceWorkflows pull request #22
Opened 2020-09-22 19:40 UTC by emomon23

2020-09-22 20:57 UTC, JoeHarstad requested changes

2020-09-22 20:57 UTC, JoeHarstad commented on public/js/tsUICommon.js
> +    const _findDomElementss = (selector) => {
What's up with Elementss and Elements?

2020-09-22 20:57 UTC, JoeHarstad commented on public/linkedin/js/linkedInApp.js
> +        if (opportunity !== null && opportunity !== undefined) {
Can't you just do if (opportunity) here?

2020-09-22 20:57 UTC, JoeHarstad commented on public/linkedin/js/linkedInPublicProfile.js
> +        result.linkedInUrl = window.location.href;
This needs to change to result.linkedIn

That's how contacts were initially created, the URL for profile is stored in a variable called "linkedIn" and our AlisonContactService expects "linkedIn" on the candidate to save.

2020-09-22 20:57 UTC, JoeHarstad commented on public/linkedin/js/linkedInPublicProfile.js
> +        result.linkedInUrl = window.location.href;
I would like to change this to "linkedInUrl" but that's A LOT of contacts to figure out how to update :) and we have to go back through all the Alison code too.

2020-09-22 20:57 UTC, JoeHarstad commented on public/linkedin/js/linkedInPublicProfileSpy.js
>  (() => {
Feel like moving this into our spies folder?

2020-09-22 20:57 UTC, JoeHarstad commented on public/linkedin/js/linkedInPublicProfileSpy.js
> +        const fullName = `${recipientName.firstName || ''}${recipientName.lastName || ''}`;
Based on the result created from function _getFirstAndLastName() you don't need the || '' here as

2020-09-22 20:57 UTC, JoeHarstad commented on public/linkedin/js/linkedInPublicProfileSpy.js
> +            console.log("Unable to record connection request, unable to scrape profile");
Shouldn't this return here?  Vs move on to the record functionality?

Can you also change this to a WARN message (so it stands out).
console.log("Unable to record connection request, unable to scrape profile", "WARN");

2020-09-22 20:57 UTC, JoeHarstad commented on public/linkedin/js/linkedInPublicProfileSpy.js
>              return;
We should probably get better at returning:  false, true, null in all our functions that "do stuff but don't have a return" so that we can properly "do other stuff" based on the success, failure, or inability to perform function duties

2020-09-22 20:57 UTC, JoeHarstad commented on public/linkedin/js/linkedInPublicProfileSpy.js
> +            return _getFirstAndLastName(startingSelector);
Let's Go Fishing!!!

2020-09-22 20:57 UTC, JoeHarstad commented on public/linkedin/js/spies/linkedInRecruiterProfileSpy.js
> +        const publicProfileLink = tsUICommon.findDomElements(linkedInSelectors.recruiterProfilePage.PROFILE_LINK);
Back to the first comment.  Why did we pluralize the singular, and double pluralize the already plural? 

This doesn't make sense.  If we're finding "elements" I would then expect us to loop over them vs handle a single element.

2020-09-22 23:07 UTC, emomon23 commented on public/js/tsUICommon.js
> +    const _findDomElementss = (selector) => {
fixed

2020-09-22 23:09 UTC, emomon23 commented on public/linkedin/js/linkedInPublicProfile.js
> +        result.linkedInUrl = window.location.href;
done

2020-09-22 23:09 UTC, emomon23 commented on public/linkedin/js/linkedInApp.js
> +        if (opportunity !== null && opportunity !== undefined) {
done

2020-09-22 23:10 UTC, emomon23 commented on public/linkedin/js/linkedInPublicProfileSpy.js
>  (() => {
let's plan another effort to create the tsWindow.js and move this

2020-09-22 23:11 UTC, emomon23 commented on public/linkedin/js/linkedInPublicProfileSpy.js
> +        const fullName = `${recipientName.firstName || ''}${recipientName.lastName || ''}`;
done

2020-09-22 23:12 UTC, emomon23 commented on public/linkedin/js/linkedInPublicProfileSpy.js
> +            console.log("Unable to record connection request, unable to scrape profile");
done

2020-09-22 23:14 UTC, emomon23 commented on public/linkedin/js/linkedInPublicProfileSpy.js
>              return;
this would be a 'void', which is kind of what 'undefined' is, it's "void of meaning", vs "null" has meaning, it's null.

2020-09-22 23:14 UTC, emomon23 commented on public/linkedin/js/linkedInPublicProfileSpy.js
> +            return _getFirstAndLastName(startingSelector);
Fish on!

2020-09-22 23:16 UTC, emomon23 commented on public/linkedin/js/spies/linkedInRecruiterProfileSpy.js
> +        const publicProfileLink = tsUICommon.findDomElements(linkedInSelectors.recruiterProfilePage.PROFILE_LINK);
because findDomElement actually can return multiple jQuery elements, which is actually what I want.   

$(aSingleElement).bind('click'...)
&
$(oneOrMoreElements).bind('click')

the 2nd one will bind to ALL of them

2020-09-23 14:52 UTC, JoeHarstad approved these changes

2020-09-23 14:52 UTC, JoeHarstad commented on public/js/tsCommon.js
> +            console.log("Unable to postMessage to Alison Hook", "WARNING");
WARN not WARNING

2020-09-23 14:56 UTC, JoeHarstad approved these changes

2020-09-23 14:56 UTC, merged